CREATE TABLE "record_fields" (
	"idx"	INTEGER UNIQUE,
	"V1_field"	TEXT,
	"V1_type"	TEXT,
	"V1_hash"	INTEGER,
	"V1_order"	INTEGER,
	PRIMARY KEY("idx" AUTOINCREMENT)
)
CREATE TABLE "record-versions" (
	"ID"	INTEGER UNIQUE,
	"NAME"	TEXT,
	"STRING"	TEXT UNIQUE,
	"e"	INTEGER,
	"m"	INTEGER,
	"u"	INTEGER,
	"n"	INTEGER,
	"FIELDS"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
)
CREATE TABLE "hash_versions" (
	"ID"	INTEGER UNIQUE,
	"NAME"	TEXT,
	"STRING"	TEXT UNIQUE,
	"e"	INTEGER,
	"m"	INTEGER,
	"u"	INTEGER,
	"n"	INTEGER,
	"ALGORITHM"	TEXT,
	"HASHSTR"	TEXT,
	"FIELDS"	TEXT,
	"HASHCMD"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT)
)
CREATE TABLE "hash-fields" (
	"ID"	INTEGER UNIQUE,
	"TIME_UNIX"	INTEGER NOT NULL,
	"DOMAIN"	TEXT,
	"HOST"	TEXT,
	"USER"	TEXT,
	"COMMAND"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
)
